config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }

  devise_for :customer, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers' => "customers#update"
    get 'customers/confirm'
    get 'customers/withdrawal'
    post 'orders/confirm' => "orders#confirm"
    get 'orders/complete' => "orders#complete"
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy]

    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show,:edit, :update]

    resources :orders, only:[:show, :update]

    resources :order_details, only: [:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {waiting_pay: 0, payed: 1, progress: 2, standby: 3, complete: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: {cannot_start: 0, waiting: 1, progress: 2, complete: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,\
      :first_name_kana, :postal_code, :address, :telephone_number, :email,\
      :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to '/admin/genres'
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payed"
      @order.order_details.update(status: 1)
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,\
            keys: [:last_name, :first_name, :last_name_kana, :first_name_kana,\
                :postal_code, :address, :telephone_number])
    end

    private

    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope.is_a?(Admin)
            admin_root_path
        else
            root_path
        end
    end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :user
            root_path
        elsif resource_or_scope == :admin
            new_admin_session_path
        else
            root_path
        end
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-6">
      <h3 style="background-color:lightgray; text-align:center;">
        <span><%= @customer.last_name %><%= @customer.first_name %></span>
        さんの会員情報編集
      </h3>
    </div>
  </div>

  <div class="container-lg">

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>会員ID</p>
      </div>

      <div class="col-3">
        <%= @customer.id %>
      </div>
    </div>

    <%= form_with model: @customer, url: admin_customer_path do |f| %>

    <div class="row", style="margin-left:310px;">
      <div class="col-3">
        <p>氏名</p>
      </div>

      <div class="col-3">
        <%= f.text_field :last_name %>
      </div>

      <div class="col-3">
        <%= f.text_field :first_name %>
      </div>
    </div>

    <div class="row", style="margin-left:310px;">
      <div class="col-3">
        <p>フリガナ</p>
      </div>

      <div class="col-3">
        <%= f.text_field :last_name_kana %>
      </div>

      <div class="col-3">
        <%= f.text_field :first_name_kana %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>郵便番号</p>
      </div>

      <div class="col-3">
        <%= f.text_field :postal_code %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>住所</p>
      </div>

      <div class="col-3">
        <%= f.text_field :address %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>電話番号</p>
      </div>

      <div class="col-3">
        <%= f.text_field :telephone_number %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>メールアドレス</p>
      </div>

      <div class="col-3">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>会員ステータス</p>
      </div>

      <div class="col-3">
        <%= f.radio_button :is_active, :true, checked: true %>
          <%= f.label :is_active, "有効" %>

        <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "退会" %>
      </div>
    </div>
    
    <div class="row align-items-center justify-content-center">
      <div class="col-3", style="padding-left:150px;">
        <%= f.submit "変更を保存", class: "btn btn-success"  %>
      </div>
    </div>

  <% end %>

  </div>

</div>

app/views/admin/customers/index.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">会員一覧</h3>
    </div>
  </div>

  <div class="container-lg">

    <div>

      <table class="table">

       <tr class="table-secondary">
         <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
       </tr>

       <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>

            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>

            <td><%= customer.email %></td>

            <td>
              <% if customer.is_active == true %>
                <p style="color:limegreen;">有効</p>
              <% else %>
                <p style="color:gray;">退会</p>
              <% end %>
            </td>
          </tr>
       <% end %>
      </table>

    </div>

  </div>

  <div class="row align-items-center justify-content-center">
    <%= paginate @customers %>
  </div>


</div>

app/views/admin/customers/show.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-5">
      <h3 style="background-color:lightgray; text-align:center;">
        <span><%= @customer.last_name %><%= @customer.first_name %></span>
          さんの会員詳細
      </h3>
    </div>
  </div>

  <div class="container-lg">

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>会員ID</p>
      </div>

      <div class="col-5">
        <%= @customer.id %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>氏名</p>
      </div>

      <div class="col-5">
        <%= @customer.last_name %> <%= @customer.first_name %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>フリガナ</p>
      </div>

      <div class="col-5">
        <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>郵便番号</p>
      </div>

      <div class="col-5">
        <%= @customer.postal_code %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>住所</p>
      </div>

      <div class="col-5">
        <%= @customer.address %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>電話番号</p>
      </div>

      <div class="col-5">
        <%= @customer.telephone_number %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>メールアドレス</p>
      </div>

      <div class="col-5">
        <%= @customer.email %>
      </div>
    </div>

    <div class="row align-items-center justify-content-center">
      <div class="col-2">
        <p>会員ステータス</p>
      </div>

      <div class="col-5">
        <% if @customer.is_active == true %>
          有効
        <% else %>
          退会
        <% end %>
      </div>
    </div>

  </div>

  <div class="row align-items-center justify-content-center">
    <div class="col-3", style="padding-left:150px;">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
    </div>

    <div class="col-3", style="padding-left:150px;">
      <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary", style: "width:200px;" %>
    </div>
  </div>

</div>