config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }

  devise_for :customer, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers' => "customers#update"
    get 'customers/confirm'
    get 'customers/withdrawal'
    post 'orders/confirm' => "orders#confirm"
    get 'orders/complete' => "orders#complete"
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy]

    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show,:edit, :update]

    resources :orders, only:[:show, :update]

    resources :order_details, only: [:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {waiting_pay: 0, payed: 1, progress: 2, standby: 3, complete: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: {cannot_start: 0, waiting: 1, progress: 2, complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to '/admin/genres'
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payed"
      @order.order_details.update(status: 1)
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,\
            keys: [:last_name, :first_name, :last_name_kana, :first_name_kana,\
                :postal_code, :address, :telephone_number])
    end

    private

    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope.is_a?(Admin)
            admin_root_path
        else
            root_path
        end
    end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :user
            root_path
        elsif resource_or_scope == :admin
            new_admin_session_path
        else
            root_path
        end
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">ジャンル編集</h3>
    </div>
  </div>
  
  <div class="row">
    
    <div class="col-2">
      <p>ジャンル名</p>
    </div>

    <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <div class="col-5", style="display:inline-block;">
        <%= f.text_field :name %>
      </div>

      <div class="col-4", style="display:inline-block; margin-left: 50px;">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    <% end %>

  </div>
  
</div>

app/views/admin/genres/index.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h4 style="background-color:lightgray; text-align:center;">ジャンル一覧・追加</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <p>ジャンル名</p>
    </div>

    <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <div class="col-5", style="display:inline-block;">
        <%= f.text_field :name %>
      </div>

      <div class="col-4", style="display:inline-block; margin-left: 50px;">
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
    <% end %>

  </div>

  <div class="row">

    <div class="col-5">

      <table class="table">

        <tr class="table-secondary">
          <th>ジャンル</th>
          <th></th>
        </tr>

        <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>

            <td>
              <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>

      </table

    </div>



  </div>



</div>

app/views/admin/items/edit.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">商品編集</h3>
    </div>
  </div>

  <div class="container-lg">

    <%= form_with model: @item, url: admin_item_path do |f| %>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品画像</p>
        </div>

        <div class="col-3">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品名</p>
        </div>

        <div class="col-3">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品説明</p>
        </div>

        <div class="col-3">
          <%= f.text_area :introduction, size: "30x7" %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>ジャンル</p>
        </div>

        <div class="col-3">
          <%= f.collection_select :genre_id, @genres, :id, :name %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>税抜価格</p>
        </div>

        <div class="col-3">
          <%= f.text_field :price %> <span>円</span>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>販売ステータス</p>
        </div>

        <div class="col-3">
          <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, "販売中" %>

          <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中" %>
        </div>
      </div>


      <div class="row align-items-center justify-content-center">
        <div class="col-3", style="padding-left:150px;">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>

    <% end %>

  </div>


</div>

app/views/admin/items/index.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">

    <div class="col-3">
      <h2 style="background-color:lightgray; text-align:center;">商品一覧</h2>
    </div>

    <div class="col-8"></div>

    <div class="col-1">
      <%= link_to "＋", new_admin_item_path, class: "btn btn-light rounded-circle p-0 btn-outline-dark",\
        style: "font-size:30px; width:3rem; height:3rem;" %>
    </div>

  </div>

  <div class="row">

    <table class="table">

      <tr class="table-secondary">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>

      <% @items.each do |item| %>

        <tr>
          <td>
            <%= item.id %>
          </td>

          <td>
            <%= link_to item.name, admin_item_path(item.id) %>
          </td>

          <td>
            <%= item.price.to_s(:delimited) %>
          </td>

          <td>
            <%= item.genre.name %>
          </td>

          <td>
            <% if item.is_active == true %>
              <p style="color:limegreen;">販売中</p>
            <% else %>
              <p style="color:silver;">販売停止中</p>
            <% end %>
          </td>
        </tr>

      <% end %>

    </table>

  </div>

  <div class="row  align-items-center justify-content-center">
    <%= paginate @items %>
  </div>



</div>

app/views/admin/items/new.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">商品新規登録</h3>
    </div>
  </div>

  <div class="container-lg">

    <%= form_with model: @item, url: admin_items_path do |f| %>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品画像</p>
        </div>

        <div class="col-3">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品名</p>
        </div>

        <div class="col-3">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>商品説明</p>
        </div>

        <div class="col-3">
          <%= f.text_area :introduction, size: "30x7" %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>ジャンル</p>
        </div>

        <div class="col-3">
          <%= f.collection_select :genre_id, @genres, :id, :name %>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>税抜価格</p>
        </div>

        <div class="col-3">
          <%= f.text_field :price %> <span>円</span>
        </div>
      </div>

      <div class="row align-items-center justify-content-center">
        <div class="col-2">
          <p>販売ステータス</p>
        </div>

        <div class="col-3">
          <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, "販売中" %>

          <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中" %>
        </div>
      </div>



      <div class="row align-items-center justify-content-center">
        <div class="col-3", style="padding-left:150px;">
          <%= f.submit '新規登録', class: "btn btn-success" %>
        </div>
      </div>

    </div>

    <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">商品詳細</h3>
    </div>
  </div>

  <div class="row">

    <div class="col-4">
      <%= image_tag @item.image, size: "300x200" %>
    </div>

    <div class="col-8">

      <div class="row">
        <div class="col-3">
          <h4>商品名</h4>
        </div>

        <div class="col-9">
          <p><%= @item.name %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-3">
          <h4>商品説明</h4>
        </div>

        <div class="col-9">
          <p><%= @item.introduction %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-3">
          <h4>ジャンル</h4>
        </div>

        <div class="col-9">
          <p><%= @item.genre.name %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-3", style="line-height:1;">
          <p style="margin:0;">税込価格</p>
          <p style="margin:0;">(税抜価格)</p>
        </div>

        <div class="col-9">
          <p><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)<span>円</span></p>
        </div>
      </div>

      <div class="row">
        <div class="col-3">
          <p>販売ステータス</p>
        </div>

        <div class="col-9">
          <p>
            <% if @item.is_active == true %>
              <p style="color:limegreen;">販売中</p>
            <% else %>
              <p style="color:silver;">販売停止中</p>
            <% end %>
          </td>
          </p>
        </div>

      </div>


      <%= link_to "編集する", edit_admin_item_path, class: "btn btn-success" %>

    </div>

  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container-lg">

  <div class="row", style="margin:20px 0;">
    <div class="col-3">
      <h3 style="background-color:lightgray; text-align:center;">注文履歴詳細</h3>
    </div>
  </div>

  <div class="row">

    <table class="table table-borderless">
      <tr>
        <td style="width:150px;">購入者</td>
        <td>
          <%= link_to admin_customer_path(@order.customer.id) do %>
            <%= @order.customer.last_name %> <%= @order.customer.first_name %>
          <% end %>
        </td>
      </tr>

      <tr>
        <td>注文日</td>
        <td>
          <%= @order.created_at.strftime('%Y/%m/%d') %>
        </td>
      </tr>

      <tr>
        <td>配送先</td>
        <td>
          〒<%= @order.shipping_postal_code %> <%= @order.shipping_address %></br>
          <%= @order.shipping_name %>
        </td>
      </tr>

      <tr>
        <td>支払方法</td>
        <td>
          <%= @order.payment_method_i18n %>
        </td>
      </tr>

      <tr>
        <td>注文ステータス</td>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
            <%= f.select :status, [["入金待ち","waiting_pay"], ["入金確認","payed"], ["製作中","progress"],\
            ["発送準備中","standby"], ["発送済み","complete"]] %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </table>

  </div>

  <div class="row">

    <div class="col-8">

      <table class="table">

        <tr class="table-secondary">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>

        <% @order.order_details.each do |order_detail| %>

          <tr>

            <td>
              <%= order_detail.item.name %>
            </td>

            <td>
              <%= (order_detail.price * 1.1).floor.to_s(:delimited) %>
            </td>

            <td>
              <%= order_detail.amount %>
            </td>

            <td>
              <%= (order_detail.price * order_detail.amount * 1.1).floor.to_s(:delimited) %>
            </td>

            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :status, [["着手不可","cannot_start"], ["製作待ち","waiting"], \
                  ["製作中","progress"], ["製作完了","complete"]] %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>

          </tr>

        <% end %>

      </table>

    </div>

    <div class="col-4">

      <table class="table">

        <tr>
          <td>商品合計</td>
          <td>
            <% @total = 0 %>
            <% @order.order_details.each do |order_detail| %>
              <% @total += (order_detail.price * order_detail.amount) %>
            <% end %>
            <%= (@total * 1.1).floor.to_s(:delimited) %>円
          </td>
        </tr>

        <tr>
          <td>送料</td>
          <td>
            <%= @order.postage %>円
          </td>
        </tr>

        <tr>
          <td>請求金額合計</td>
          <td>
            <%= ((@total * 1.1) + @order.postage).floor.to_s(:delimited) %>円
          </td>
        </tr>

      </table>

    </div>

  </div>

</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>