config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }

  devise_for :customer, skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers' => "customers#update"
    get 'customers/confirm'
    get 'customers/withdrawal'
    post 'orders/confirm' => "orders#confirm"
    get 'orders/complete' => "orders#complete"
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy]

    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, only: [:index, :show,:edit, :update]

    resources :orders, only:[:show, :update]

    resources :order_details, only: [:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {waiting_pay: 0, payed: 1, progress: 2, standby: 3, complete: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: {cannot_start: 0, waiting: 1, progress: 2, complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to '/admin/genres'
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,\
            keys: [:last_name, :first_name, :last_name_kana, :first_name_kana,\
                :postal_code, :address, :telephone_number])
    end

    private

    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope.is_a?(Admin)
            admin_root_path
        else
            root_path
        end
    end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :user
            root_path
        elsif resource_or_scope == :admin
            new_admin_session_path
        else
            root_path
        end
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="height: 150px", class="container-fluid w-100 shadow-sm">

      <% if admin_signed_in? %>
        <div class="row h-100 w-100">

          <div class="col-3 d-flex align-items-center justify-content-center">
            <h1>LOGO</h1>
          </div>

          <div class="col-4">
          </div>

          <div class="col-5 d-flex align-items-center justify-content-center">
            <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary w-20 m-1" %>

            <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary w-20 m-1" %>

            <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary w-20 m-1" %>

            <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary w-20 m-1" %>

            <%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-secondary w-20 m-1" %>
          </div>
        </div>

      <% elsif customer_signed_in? %>

          <div class="row h-100 w-100">

            <div class="col-3 d-flex align-items-center justify-content-center">
              <%= link_to "LOGO", root_path, class: "navbar-brand border" %>
            </div>

            <div class="col-4 d-flex align-items-center justify-content-center">
              <p>ようこそ、<strong><%= current_customer.last_name %></strong>さん！</p>
            </div>

            <div class="col-5 d-flex align-items-center justify-content-center">
              <%= link_to "マイページ", customers_path, class: "btn btn-outline-secondary w-20 m-1" %>

              <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary m-1" %>

              <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary m-1" %>

              <%= link_to "ログアウト", destroy_customer_session_path, class: "btn btn-outline-secondary m-1" %>
            </div>

          </div>

      <% else %>

        <div class="row h-100 w-100">

          <div class="col-3 d-flex align-items-center justify-content-center">
            <%= link_to "LOGO", root_path, class: "navbar-brand border" %>
          </div>

          <div class="col-4">
          </div>

          <div class="col-5 d-flex align-items-center justify-content-center">
              <%= link_to "About", about_path, class: "btn btn-outline-secondary w-20 m-1" %>

              <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary m-1" %>


              <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary m-1" %>

              <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary m-1" %>
          </div>

        </div>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>